name: Tests CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test
      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"      
      - name: Merge current commit back to dev branch
        run: |
          export HASH=$(git rev-parse --short HEAD)
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff $HASH -m "chore: auto-merge deployment back to dev"
          git push origin -f main